name: "Setup Go"
description: "Custom action to set up Go environment"
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.23"
